In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = requests.get("https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc")

In [4]:
url

In [5]:
soup = BeautifulSoup(url.content)

In [6]:
titles = []

for i in soup.find_all("h3",class_="lister-item-header"):
    titles.append(i.text.split("\n")[2])
    
titles

['The Shawshank Redemption',
 'The Godfather',
 'The Dark Knight',
 'The Lord of the Rings: The Return of the King',
 'The Godfather Part II',
 "Schindler's List",
 '12 Angry Men',
 'Pulp Fiction',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Fight Club',
 'Inception',
 'Forrest Gump',
 'The Lord of the Rings: The Two Towers',
 'Il buono, il brutto, il cattivo',
 'Goodfellas',
 'The Matrix',
 "One Flew Over the Cuckoo's Nest",
 'The Empire Strikes Back',
 'Interstellar',
 "It's a Wonderful Life",
 'Se7en',
 'Star Wars',
 'The Silence of the Lambs',
 'The Green Mile',
 'Terminator 2: Judgment Day',
 'Saving Private Ryan',
 'Cidade de Deus',
 'Sen to Chihiro no kamikakushi',
 'La vita è bella',
 'Shichinin no samurai',
 'Seppuku',
 'Whiplash',
 'Léon',
 'Gisaengchung',
 'Gladiator',
 'Back to the Future',
 'The Prestige',
 'Apocalypse Now',
 'The Departed',
 'Alien',
 'The Usual Suspects',
 'American History X',
 'The Lion King',
 'The Intouchables',
 'The Pianist',
 'Once Upon a Time in the West',
 'Psycho',
 'Casablanca',
 'Hotaru no haka',
 'Rear Window']

In [7]:
year = []

for i in soup.find_all("span",class_="lister-item-year text-muted unbold"):
    year.append(i.text)
    
year

['(1994)',
 '(1972)',
 '(2008)',
 '(2003)',
 '(1974)',
 '(1993)',
 '(1957)',
 '(1994)',
 '(2001)',
 '(1999)',
 '(2010)',
 '(1994)',
 '(2002)',
 '(1966)',
 '(1990)',
 '(1999)',
 '(1975)',
 '(1980)',
 '(2014)',
 '(1946)',
 '(1995)',
 '(1977)',
 '(1991)',
 '(1999)',
 '(1991)',
 '(1998)',
 '(2002)',
 '(2001)',
 '(1997)',
 '(1954)',
 '(1962)',
 '(2014)',
 '(1994)',
 '(2019)',
 '(2000)',
 '(1985)',
 '(2006)',
 '(1979)',
 '(2006)',
 '(1979)',
 '(1995)',
 '(1998)',
 '(1994)',
 '(2011)',
 '(2002)',
 '(1968)',
 '(1960)',
 '(1942)',
 '(1988)',
 '(1954)']

In [8]:
rating = []

for i in soup.find_all("div",class_="inline-block ratings-imdb-rating"):
    rating.append(i.text.split("\n")[2])
    
rating

['9.3',
 '9.2',
 '9.0',
 '9.0',
 '9.0',
 '9.0',
 '9.0',
 '8.9',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5']

In [9]:
url = requests.get("https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc&start=51&ref_=adv_nxt")

In [10]:
url

In [11]:
soup = BeautifulSoup(url.content)

In [12]:
for i in soup.find_all("h3",class_="lister-item-header"):
    titles.append(i.text.split("\n")[2])
    
titles

['The Shawshank Redemption',
 'The Godfather',
 'The Dark Knight',
 'The Lord of the Rings: The Return of the King',
 'The Godfather Part II',
 "Schindler's List",
 '12 Angry Men',
 'Pulp Fiction',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Fight Club',
 'Inception',
 'Forrest Gump',
 'The Lord of the Rings: The Two Towers',
 'Il buono, il brutto, il cattivo',
 'Goodfellas',
 'The Matrix',
 "One Flew Over the Cuckoo's Nest",
 'The Empire Strikes Back',
 'Interstellar',
 "It's a Wonderful Life",
 'Se7en',
 'Star Wars',
 'The Silence of the Lambs',
 'The Green Mile',
 'Terminator 2: Judgment Day',
 'Saving Private Ryan',
 'Cidade de Deus',
 'Sen to Chihiro no kamikakushi',
 'La vita è bella',
 'Shichinin no samurai',
 'Seppuku',
 'Whiplash',
 'Léon',
 'Gisaengchung',
 'Gladiator',
 'Back to the Future',
 'The Prestige',
 'Apocalypse Now',
 'The Departed',
 'Alien',
 'The Usual Suspects',
 'American History X',
 'The Lion King',
 'The Intouchables',
 'The Pianist',
 'Once Upon a Time in the West',
 'Psycho',
 'Casablanca',
 'Hotaru no haka',
 'Rear Window',
 'Nuovo Cinema Paradiso',
 'Modern Times',
 'City Lights',
 'Avengers: Endgame',
 'Raiders of the Lost Ark',
 'Joker',
 'Django Unchained',
 'American Beauty',
 'Braveheart',
 'The Dark Knight Rises',
 'Spider-Man: Into the Spider-Verse',
 'Aliens',
 'Avengers: Infinity War',
 'The Shining',
 'Oldeuboi',
 'Memento',
 'Coco',
 'Amadeus',
 'Idi i smotri',
 'Kimi no Na wa.',
 '3 Idiots',
 'WALL·E',
 'The Lives of Others',
 'Capharnaüm',
 'Mononoke-hime',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Sunset Blvd.',
 'Das Boot',
 'Witness for the Prosecution',
 'Paths of Glory',
 'The Great Dictator',
 'Tengoku to jigoku',
 'Top Gun: Maverick',
 'Good Will Hunting',
 'Inglourious Basterds',
 'Requiem for a Dream',
 'Eternal Sunshine of the Spotless Mind',
 '2001: A Space Odyssey',
 'Reservoir Dogs',
 'Jagten',
 "Singin' in the Rain",
 'Once Upon a Time in America',
 'North by Northwest',
 'Star Wars: Episode VI - Return of the Jedi',
 'Toy Story',
 'Vertigo',
 'Lawrence of Arabia',
 'Citizen Kane',
 'Toy Story 3',
 'M - Eine Stadt sucht einen Mörder']

In [13]:
for i in soup.find_all("span",class_="lister-item-year text-muted unbold"):
    year.append(i.text)
    
year

['(1994)',
 '(1972)',
 '(2008)',
 '(2003)',
 '(1974)',
 '(1993)',
 '(1957)',
 '(1994)',
 '(2001)',
 '(1999)',
 '(2010)',
 '(1994)',
 '(2002)',
 '(1966)',
 '(1990)',
 '(1999)',
 '(1975)',
 '(1980)',
 '(2014)',
 '(1946)',
 '(1995)',
 '(1977)',
 '(1991)',
 '(1999)',
 '(1991)',
 '(1998)',
 '(2002)',
 '(2001)',
 '(1997)',
 '(1954)',
 '(1962)',
 '(2014)',
 '(1994)',
 '(2019)',
 '(2000)',
 '(1985)',
 '(2006)',
 '(1979)',
 '(2006)',
 '(1979)',
 '(1995)',
 '(1998)',
 '(1994)',
 '(2011)',
 '(2002)',
 '(1968)',
 '(1960)',
 '(1942)',
 '(1988)',
 '(1954)',
 '(1988)',
 '(1936)',
 '(1931)',
 '(2019)',
 '(1981)',
 '(I) (2019)',
 '(2012)',
 '(1999)',
 '(1995)',
 '(2012)',
 '(2018)',
 '(1986)',
 '(2018)',
 '(1980)',
 '(2003)',
 '(2000)',
 '(I) (2017)',
 '(1984)',
 '(1985)',
 '(2016)',
 '(2009)',
 '(2008)',
 '(2006)',
 '(2018)',
 '(1997)',
 '(1964)',
 '(1950)',
 '(1981)',
 '(1957)',
 '(1957)',
 '(1940)',
 '(1963)',
 '(2022)',
 '(1997)',
 '(2009)',
 '(2000)',
 '(2004)',
 '(1968)',
 '(1992)',
 '(2012)',
 '(1952)',
 '(1984)',
 '(1959)',
 '(1983)',
 '(1995)',
 '(1958)',
 '(1962)',
 '(1941)',
 '(2010)',
 '(1931)']

In [14]:
for i in soup.find_all("div",class_="inline-block ratings-imdb-rating"):
    rating.append(i.text.split("\n")[2])
    
rating

['9.3',
 '9.2',
 '9.0',
 '9.0',
 '9.0',
 '9.0',
 '9.0',
 '8.9',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3']

In [15]:
print(len(titles),len(year),len(rating))

100 100 100

In [16]:
import pandas as pd

In [17]:
data = pd.DataFrame({"Titles":titles,"Rating":rating,"Year of Release":year})
data

                                           Titles Rating Year of Release
0                        The Shawshank Redemption    9.3          (1994)
1                                   The Godfather    9.2          (1972)
2                                 The Dark Knight    9.0          (2008)
3   The Lord of the Rings: The Return of the King    9.0          (2003)
4                           The Godfather Part II    9.0          (1974)
..                                            ...    ...             ...
95                                        Vertigo    8.3          (1958)
96                             Lawrence of Arabia    8.3          (1962)
97                                   Citizen Kane    8.3          (1941)
98                                    Toy Story 3    8.3          (2010)
99              M - Eine Stadt sucht einen Mörder    8.3          (1931)

[100 rows x 3 columns]

In [18]:
data.to_csv("TOP 100 IMDB")